package ingest

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/MatteoAdamo82/loom/internal/extract"
	"github.com/MatteoAdamo82/loom/internal/llm"
	"github.com/MatteoAdamo82/loom/internal/storage"
)

// Result summarizes what an ingest run produced. Consumers can log it or
// render it to the CLI.
type Result struct {
	Source          *storage.Source
	ChunksCreated   int
	NotesCreated    []*storage.Note
	NotesUpdated    []*storage.Note
	EntitiesLinked  int
	Deduplicated    bool // true when the source was already present (no-op)
}

type Pipeline struct {
	Store     *storage.Store
	Registry  *extract.Registry
	LLM       llm.Client
	ChunkCfg  ChunkConfig
	MaxAnalyze int // max chars passed to the analyzer (protects LLM ctx)
}

// NewPipeline wires a pipeline with sensible defaults.
func NewPipeline(store *storage.Store, client llm.Client) *Pipeline {
	return &Pipeline{
		Store:      store,
		Registry:   extract.DefaultRegistry(),
		LLM:        client,
		ChunkCfg:   ChunkConfig{MaxTokens: 500, Overlap: 50},
		MaxAnalyze: 12000,
	}
}

// Ingest executes the full pipeline on the file at path.
func (p *Pipeline) Ingest(ctx context.Context, path string) (*Result, error) {
	ext, err := p.Registry.Resolve(path)
	if err != nil {
		return nil, err
	}
	doc, err := ext.Extract(path)
	if err != nil {
		return nil, err
	}

	// 1. Dedup by hash.
	if existing, err := p.Store.GetSourceByHash(ctx, doc.Hash); err == nil && existing != nil {
		return &Result{Source: existing, Deduplicated: true}, nil
	} else if err != nil && !errors.Is(err, storage.ErrNotFound) {
		return nil, err
	}

	// 2. Persist the raw source.
	src := &storage.Source{
		URI:     doc.URI,
		Kind:    doc.Kind,
		Title:   doc.Title,
		Content: doc.Content,
		Hash:    doc.Hash,
	}
	if err := p.Store.CreateSource(ctx, src); err != nil {
		return nil, err
	}

	result := &Result{Source: src}

	// 3. Chunk and index.
	for _, ch := range Split(doc.Content, p.ChunkCfg) {
		pos := ch.Position
		tokens := ch.Tokens
		srcID := src.ID
		c := &storage.Chunk{
			SourceID: &srcID,
			Content:  ch.Content,
			Position: pos,
			Tokens:   tokens,
		}
		if err := p.Store.CreateChunk(ctx, c); err != nil {
			return nil, err
		}
		if err := p.Store.IndexChunk(ctx, c, doc.Title); err != nil {
			return nil, err
		}
		result.ChunksCreated++
	}

	// 4. LLM analyzer pass.
	analyzeText := doc.Content
	if p.MaxAnalyze > 0 && len(analyzeText) > p.MaxAnalyze {
		analyzeText = analyzeText[:p.MaxAnalyze]
	}
	analysis, err := Analyze(ctx, p.LLM, analyzeText)
	if err != nil {
		return nil, fmt.Errorf("analyze: %w", err)
	}
	if analysis.Title != "" {
		src.Title = analysis.Title
	}

	// 5. Create a summary note per source.
	summarySlug := uniqueSlug(ctx, p.Store, Slugify(src.Title+"-summary"))
	summary := &storage.Note{
		Slug:     summarySlug,
		Title:    src.Title,
		Kind:     "summary",
		Content:  fmt.Sprintf("%s\n\n_Source: %s_", analysis.Summary, src.URI),
		Summary:  analysis.Summary,
		Keywords: analysis.Keywords,
	}
	if err := p.Store.CreateNote(ctx, summary); err != nil {
		return nil, err
	}
	if err := p.Store.IndexNote(ctx, summary); err != nil {
		return nil, err
	}
	result.NotesCreated = append(result.NotesCreated, summary)

	// summary → source link (derived-from)
	srcID := src.ID
	if err := p.Store.CreateLink(ctx, &storage.Link{
		FromNoteID:  &summary.ID,
		ToSourceID:  &srcID,
		Kind:        storage.LinkDerivedFrom,
		Context:     "generated by ingest analyzer",
	}); err != nil {
		return nil, err
	}

	// 6. Find-or-create entity stubs, linked from summary.
	for _, e := range analysis.Entities {
		entity, created, err := p.findOrCreateEntity(ctx, e)
		if err != nil {
			return nil, err
		}
		if created {
			result.NotesCreated = append(result.NotesCreated, entity)
		}

		if err := p.Store.CreateLink(ctx, &storage.Link{
			FromNoteID: &summary.ID,
			ToNoteID:   &entity.ID,
			Kind:       storage.LinkWikilink,
			Context:    fmt.Sprintf("mentioned in %q", src.Title),
		}); err != nil {
			// Duplicate wikilinks are allowed to fail silently (unique index).
			if !isUniqueViolation(err) {
				return nil, err
			}
		} else {
			result.EntitiesLinked++
		}

		// entity → source citation (lets queries trace back to raw text)
		if err := p.Store.CreateLink(ctx, &storage.Link{
			FromNoteID: &entity.ID,
			ToSourceID: &srcID,
			Kind:       storage.LinkCitation,
			Context:    fmt.Sprintf("cited by %s", summary.Slug),
		}); err != nil && !isUniqueViolation(err) {
			return nil, err
		}
	}

	// 7. Log the operation.
	details, _ := json.Marshal(map[string]any{
		"source_id":       src.ID,
		"chunks":          result.ChunksCreated,
		"notes_created":   len(result.NotesCreated),
		"entities_linked": result.EntitiesLinked,
	})
	_ = p.Store.LogOperation(ctx, &storage.Operation{
		Kind:    "ingest",
		Actor:   p.LLM.Name(),
		Summary: fmt.Sprintf("Ingested %s", src.Title),
		Details: details,
	})

	return result, nil
}

// findOrCreateEntity returns a note for the given entity, creating a stub if
// none exists. We do a BM25 search by name + alias fallback; if no match, we
// materialize a minimal note and let future ingests / the lint pass flesh it
// out.
func (p *Pipeline) findOrCreateEntity(ctx context.Context, e Entity) (*storage.Note, bool, error) {
	slug := Slugify(e.Name)
	if slug == "" || slug == "untitled" {
		return nil, false, fmt.Errorf("entity %q yields empty slug", e.Name)
	}
	if existing, err := p.Store.GetNoteBySlug(ctx, slug); err == nil {
		return existing, false, nil
	} else if !errors.Is(err, storage.ErrNotFound) {
		return nil, false, err
	}

	n := &storage.Note{
		Slug:     slug,
		Title:    e.Name,
		Kind:     entityKind(e.Kind),
		Content:  fmt.Sprintf("_Stub for %s. Expand during future ingests._", e.Name),
		Summary:  fmt.Sprintf("%s (%s)", e.Name, e.Kind),
		Keywords: []string{strings.ToLower(e.Kind)},
	}
	if err := p.Store.CreateNote(ctx, n); err != nil {
		return nil, false, err
	}
	if err := p.Store.IndexNote(ctx, n); err != nil {
		return nil, false, err
	}
	return n, true, nil
}

func entityKind(k string) string {
	switch k {
	case "person", "organization", "product", "place", "event", "work", "concept":
		return "entity"
	default:
		return "entity"
	}
}

// uniqueSlug appends -2, -3, ... until the slug is free.
func uniqueSlug(ctx context.Context, store *storage.Store, base string) string {
	if base == "" {
		base = "untitled"
	}
	candidate := base
	for i := 2; ; i++ {
		_, err := store.GetNoteBySlug(ctx, candidate)
		if errors.Is(err, storage.ErrNotFound) {
			return candidate
		}
		candidate = fmt.Sprintf("%s-%d", base, i)
	}
}

func isUniqueViolation(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "unique constraint") || strings.Contains(msg, "unique")
}
