package ingest

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/MatteoAdamo82/loom/internal/extract"
	"github.com/MatteoAdamo82/loom/internal/llm"
	"github.com/MatteoAdamo82/loom/internal/storage"
)

// Result summarizes what an ingest run produced. Consumers can log it or
// render it to the CLI.
type Result struct {
	Source         *storage.Source
	ChunksCreated  int
	NotesCreated   []*storage.Note
	NotesUpdated   []*storage.Note
	EntitiesLinked int
	Deduplicated   bool // true when the source was already present (no-op)
}

type Pipeline struct {
	Store      *storage.Store
	Registry   *extract.Registry
	LLM        llm.Client
	ChunkCfg   ChunkConfig
	MaxAnalyze int // max chars passed to the analyzer (protects LLM ctx)
}

// NewPipeline wires a pipeline with sensible defaults.
func NewPipeline(store *storage.Store, client llm.Client) *Pipeline {
	return &Pipeline{
		Store:      store,
		Registry:   extract.DefaultRegistry(),
		LLM:        client,
		ChunkCfg:   ChunkConfig{MaxTokens: 500, Overlap: 50},
		MaxAnalyze: 12000,
	}
}

// Ingest executes the full pipeline on the file at path.
//
// Ordering guarantees: the LLM analyze call happens BEFORE any database
// writes, and every write is batched inside a single SQLite transaction. If
// extract, dedup, or analyze fail, the database is left unchanged; if a
// downstream write fails, the transaction rolls back and leaves nothing
// behind. Retries after a transient LLM failure therefore behave correctly.
func (p *Pipeline) Ingest(ctx context.Context, path string) (*Result, error) {
	// 1. Extract (no DB).
	ext, err := p.Registry.Resolve(path)
	if err != nil {
		return nil, err
	}
	doc, err := ext.Extract(path)
	if err != nil {
		return nil, err
	}

	// 2. Dedup by hash (read-only query, no tx).
	if existing, err := p.Store.GetSourceByHash(ctx, doc.Hash); err == nil && existing != nil {
		return &Result{Source: existing, Deduplicated: true}, nil
	} else if err != nil && !errors.Is(err, storage.ErrNotFound) {
		return nil, err
	}

	// 3. LLM analyze (no DB yet — failure here is safe to retry).
	analyzeText := doc.Content
	if p.MaxAnalyze > 0 && len(analyzeText) > p.MaxAnalyze {
		analyzeText = analyzeText[:p.MaxAnalyze]
	}
	analysis, err := Analyze(ctx, p.LLM, analyzeText)
	if err != nil {
		return nil, fmt.Errorf("analyze: %w", err)
	}

	// Build the source row in memory with the analyzer's canonical title
	// applied, so we don't need a follow-up UPDATE.
	title := doc.Title
	if analysis.Title != "" {
		title = analysis.Title
	}
	src := &storage.Source{
		URI:     doc.URI,
		Kind:    doc.Kind,
		Title:   title,
		Content: doc.Content,
		Hash:    doc.Hash,
	}

	// 4. Atomic write phase.
	result := &Result{Source: src}
	chunks := Split(doc.Content, p.ChunkCfg)

	err = p.Store.WithTx(ctx, func(tx *storage.Tx) error {
		if err := tx.CreateSource(ctx, src); err != nil {
			return err
		}

		for _, ch := range chunks {
			pos := ch.Position
			tokens := ch.Tokens
			srcID := src.ID
			c := &storage.Chunk{
				SourceID: &srcID,
				Content:  ch.Content,
				Position: pos,
				Tokens:   tokens,
			}
			if err := tx.CreateChunk(ctx, c); err != nil {
				return err
			}
			if err := tx.IndexChunk(ctx, c, src.Title); err != nil {
				return err
			}
			result.ChunksCreated++
		}

		summarySlug, err := uniqueSlugTx(ctx, tx, Slugify(src.Title+"-summary"))
		if err != nil {
			return err
		}
		summary := &storage.Note{
			Slug:     summarySlug,
			Title:    src.Title,
			Kind:     "summary",
			Content:  fmt.Sprintf("%s\n\n_Source: %s_", analysis.Summary, src.URI),
			Summary:  analysis.Summary,
			Keywords: analysis.Keywords,
		}
		if err := tx.CreateNote(ctx, summary); err != nil {
			return err
		}
		if err := tx.IndexNote(ctx, summary); err != nil {
			return err
		}
		result.NotesCreated = append(result.NotesCreated, summary)

		srcID := src.ID
		if err := tx.CreateLink(ctx, &storage.Link{
			FromNoteID: &summary.ID,
			ToSourceID: &srcID,
			Kind:       storage.LinkDerivedFrom,
			Context:    "generated by ingest analyzer",
		}); err != nil {
			return err
		}

		for _, e := range analysis.Entities {
			entity, created, err := findOrCreateEntityTx(ctx, tx, e)
			if err != nil {
				return err
			}
			if created {
				result.NotesCreated = append(result.NotesCreated, entity)
			}

			if err := tx.CreateLink(ctx, &storage.Link{
				FromNoteID: &summary.ID,
				ToNoteID:   &entity.ID,
				Kind:       storage.LinkWikilink,
				Context:    fmt.Sprintf("mentioned in %q", src.Title),
			}); err != nil {
				if !isUniqueViolation(err) {
					return err
				}
			} else {
				result.EntitiesLinked++
			}

			if err := tx.CreateLink(ctx, &storage.Link{
				FromNoteID: &entity.ID,
				ToSourceID: &srcID,
				Kind:       storage.LinkCitation,
				Context:    fmt.Sprintf("cited by %s", summary.Slug),
			}); err != nil && !isUniqueViolation(err) {
				return err
			}
		}

		details, _ := json.Marshal(map[string]any{
			"source_id":       src.ID,
			"chunks":          result.ChunksCreated,
			"notes_created":   len(result.NotesCreated),
			"entities_linked": result.EntitiesLinked,
		})
		return tx.LogOperation(ctx, &storage.Operation{
			Kind:    "ingest",
			Actor:   p.LLM.Name(),
			Summary: fmt.Sprintf("Ingested %s", src.Title),
			Details: details,
		})
	})
	if err != nil {
		return nil, err
	}

	return result, nil
}

// findOrCreateEntityTx returns a note for the given entity, creating a stub
// if none exists. All operations go through the provided transaction so the
// enclosing ingest remains atomic.
func findOrCreateEntityTx(ctx context.Context, tx *storage.Tx, e Entity) (*storage.Note, bool, error) {
	slug := Slugify(e.Name)
	if slug == "" || slug == "untitled" {
		return nil, false, fmt.Errorf("entity %q yields empty slug", e.Name)
	}
	if existing, err := tx.GetNoteBySlug(ctx, slug); err == nil {
		return existing, false, nil
	} else if !errors.Is(err, storage.ErrNotFound) {
		return nil, false, err
	}

	n := &storage.Note{
		Slug:     slug,
		Title:    e.Name,
		Kind:     entityKind(e.Kind),
		Content:  fmt.Sprintf("_Stub for %s. Expand during future ingests._", e.Name),
		Summary:  fmt.Sprintf("%s (%s)", e.Name, e.Kind),
		Keywords: []string{strings.ToLower(e.Kind)},
	}
	if err := tx.CreateNote(ctx, n); err != nil {
		return nil, false, err
	}
	if err := tx.IndexNote(ctx, n); err != nil {
		return nil, false, err
	}
	return n, true, nil
}

func entityKind(k string) string {
	switch k {
	case "person", "organization", "product", "place", "event", "work", "concept":
		return "entity"
	default:
		return "entity"
	}
}

// uniqueSlugTx appends -2, -3, ... until the slug is free within the tx.
func uniqueSlugTx(ctx context.Context, tx *storage.Tx, base string) (string, error) {
	if base == "" {
		base = "untitled"
	}
	candidate := base
	for i := 2; ; i++ {
		_, err := tx.GetNoteBySlug(ctx, candidate)
		if errors.Is(err, storage.ErrNotFound) {
			return candidate, nil
		}
		if err != nil {
			return "", err
		}
		candidate = fmt.Sprintf("%s-%d", base, i)
	}
}

func isUniqueViolation(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "unique constraint") || strings.Contains(msg, "unique")
}
